---
- name: install sudo
  yum: name=sudo state=present
- name: install git
  yum: name=git state=present
- name: add jenkins users
  user: name=jenkins shell=/bin/bash groups=wheel append=yes
- name: Install Java 1.8.0
  yum: name=java-1.8.0-openjdk state=present
- name: Install bzip2
  yum: name=bzip2 state=present
- name: Create root ssh directory
  file: path=/home/root/.ssh state=directory
- name: Create jenkins ssh directory
  file: path=/home/jenkins/.ssh state=directory
- name: Copy sudoers
  copy: src=sudoers dest=/etc/sudoers
