---
- name: Install rubygems
  yum: name=rubygems state=latest
- name: Install gcc
  yum: name=gcc state=latest
- name: Install ruby-devel
  yum: name=ruby-devel state=latest
- name: Install make
  yum: name=make state=latest
- name: Update ruby gems
  command: gem update --system creates=/opt/rubygemsinstall.txt
- name: Create rubygems checkfile
  file: path=/opt/rubygemsinstall.txt state=touch
  changed_when: False
- name: Install bundler gem
  gem: name=bundler state=latest user_install=no
- name: Install which package
  yum: name=which state=latest
- name: Copy rvm install script
  copy: src=rvm.sh dest=/opt/rvm.sh mode=0755
- name: Install RVM
  shell: /usr/bin/env bash /opt/rvm.sh
