---
# Installation steps based on https://docs.docker.com/engine/installation/linux/ubuntulinux/

- name: Install apt-transport-https to ensure apt works with https
  apt: name=apt-transport-https state=present

- name: Install ca-certificates
  apt: name=ca-certificates state=present

- name: Install python-pip
  apt: name=python-pip state=present

- name: Add docker apt key
  apt_key: keyserver=keyserver.ubuntu.com id={{ docker_apt_key_id }}

- name: Add docker apt repo to sources list
  apt_repository: repo="{{ docker_apt_repo }}" update_cache=yes state=present

- name: Ensure lxc-docker is not installed
  apt: name=lxc-docker state=absent purge=yes

- name: Install recommended linux-image-extra kernel packages
  apt: name="{{ item }}" state=present
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - "linux-image-extra-virtual"

- name: Install apparmor
  apt: name=apparmor state=present

- name: Install docker-engine
  apt: name=docker-engine={{ docker_engine_version|default('*') }} state=present

# WARN: docker-compose pip package >= 1.10.0 installs docker pip package which
#       conflicts with docker-py required by Ansible docker_container module.
#       So install docker-compose binary directly as workaround.
#- name: Install docker-compose
#  pip: name=docker-compose version={{ docker_compose_version }} state=present

- name: Install docker-compose
  get_url:
    url:   "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest:  /usr/local/bin/docker-compose
    owner: root
    group: root
    mode:  0755

- name: Install docker api client
  pip: name=docker-py version={{ docker_api_version }} state=present
  when: docker_api_install or docker_compose_version_major_minor|float <= 1.10

- name: Remove obsolete docker init.d service
  file: dest=/etc/init.d/docker state=absent

- name: Add users to docker group
  user: name={{ item }} groups=docker append=yes createhome=no
  with_items: "{{ docker_allow_users }}"

- debug: var=docker_engine_opts

- name: Update Docker upstart config file
  template: src=etc.default.docker.j2 dest=/etc/default/docker owner=root group=root mode=0644
  when: ansible_distribution_major_version|int < 16
  notify: Restart docker

- name: Create directory for docker service supplementary config
  file:
    path:  /etc/systemd/system/docker.service.d
    owner: root
    group: root
    mode:  0755
    state: directory
  when: ansible_distribution_major_version|int >= 16

- name: Create docker service supplementary config file
  template:
    src:   docker.service.conf.j2
    dest:  /etc/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode:  0644
  when: ansible_distribution_major_version|int >= 16
  register: supplementary
  notify:
    - Reload systemd
    - Restart docker

- name: Reload systemd if docker service supplementary config file changes
  command: systemctl daemon-reload
  when: supplementary|changed and ansible_distribution_major_version|int >= 16
