---

- name: Start swarm manager container
  docker_container:
    name:    swarm-manager
    image:   "swarm:{{ docker_swarm_image_version }}"
    ports:
      - "{{ docker_swarm_port }}:2375"
    command: "{{ docker_swarm_manager_command }}"
    restart_policy: "unless-stopped"
    state:   started
  when: docker_swarm_manager


- name: Start swarm node container
  docker_container:
    name:    swarm-node
    image:   "swarm:{{ docker_swarm_image_version }}"
    command: "{{ docker_swarm_node_command }}"
    restart_policy: "unless-stopped"
    state:   started
  when: docker_swarm_node
