---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: smanager
    driver:
      network:
        - ["private_network", { ip: "172.29.129.184" }]
  - name: snode
    driver:
      network:
        - ["private_network", { ip: "172.29.129.185" }]
