---
galaxy_info:
  author: "Ogonna Iwunze"
  company: EqualExperts
  license: BSD
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  categories:
    - docker
dependencies: []
  
